#!/usr/bin/env bash
# This script checks if all C and C++ files are compiled with optimizations.
# Usage:
# 0. Edit: LLVM_BIN_PATH to point to the llvm binary location which contains the "real" clang we should
# dispatch to.
# 1. Create two symlinks to this file: wrapper-clang and wrapper-clang++
# 2. export TARGET_CC=/path/to/wrapper-clang
#    export TARGET_CXX=/path/to/wrapper-clang++
#    export MOZJS_FROM_SOURCE <- to avoid using prebuilt mozjs artifact.
# 3. Run ./mach build --release (or other optimising build profile)



LOG_FILE=/Users/jschwender/Dev/servo/build-script-issues.txt
FAIL_BUILD=false
LLVM_BIN_PATH=/usr/bin
#LLVM_BIN_PATH="/Users/jschwender/Applications/DevEco-Studio.app/Contents/sdk/default/openharmony/native/llvm/bin"
REAL_CLANG_PATH="${LLVM_BIN_PATH}/clang"
REAL_CLANGCPP_PATH="${LLVM_BIN_PATH}/clang++"

# Pending better name. Actually does not fail build if FAIL_BUILD is not true-ish
fail_build() {
  case "${FAIL_BUILD:-}" in
    1|true|TRUE|yes|YES|on|ON)
      exit 1
      ;;
  esac
}

# We use the same wrapper for clang and clang++, so we check the symlink name
# to determine which executable to dispatch to.
BASENAME=$(basename "$0")
if [[ "${BASENAME}" == *clang ]];
then
  COMPILER_PATH="${REAL_CLANG_PATH}"
elif [[ "${BASENAME}" == *clang++ ]];
then
  COMPILER_PATH="${REAL_CLANGCPP_PATH}"
else
  echo "Error: basename ${BASENAME} - unable to determine if clang or clang++"
  exit 1
fi

opt_level=""
for flag in "$@"
do
    if [[ "${flag}" =~  ^-O([0-3sg]|fast)?$ ]]; then
      opt_level="${flag}"
    elif [[ "${flag}" =~ conftest.*\.c(pp)?$ ]]; then
        # autoconf configure check
        skip_check="SKIP"
        break
    elif [[ "${flag}" =~ aws-lc-sys-.*/aws-lc/tests/.*\.c(pp)?$ ]]; then
        skip_check="SKIP"
        break
    elif [[ "${flag}" =~ aws-lc-sys-.*/jitterentropy/jitterentropy-library/src/jitterentropy-.*.c$ ]]; then
        # Apparently this library purposefully requires `-O0`
        skip_check="SKIP"
        break
    elif [[ "${flag}" == "-Wl,"* ]]; then
         skip_check="SKIP"
         break
    elif [[ "${flag}" == "-E" ]]; then
        # We are in preprocessor only mode, so optimizations don't matter
        skip_check="SKIP"
        break
    fi
done

if [[ "$*" == "--version" || "$*" == "--print-prog-name"* || "$*" == "-?" ]]; then
  skip_check="SKIP"
fi

if [[ "${skip_check}" == "SKIP" ]]; then
    # Don't care about opt level
    :
elif [[ "${opt_level}" == "-Ofast" ]]; then
    echo "clang was supposed to be invoked with -Ofast! We want standard compliance." >> "${LOG_FILE}"
    echo "All options: " "$@" >> "${LOG_FILE}"
    fail_build
elif [[ "${opt_level}" == "-O0" || "${opt_level}" == "" || "${opt_level}" == "-O" || "${opt_level}" == "-Og" ]]; then
    echo "Optimisations were disabled: " "$@" >> "${LOG_FILE}"
    fail_build
elif [[ "${opt_level}" == "-O1" ]]; then
  echo "Warning: Source files will be compiled with -O1: "  "$@" >> "${LOG_FILE}"
  fail_build
fi

# echo "Last opt level was: ${opt_level}"

exec "${COMPILER_PATH}" "$@"
