[package]
name = "simpleservo_napi"
version = "0.0.1"
authors = ["The Servo Project Developers"]
license = "MPL-2.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
name = "simpleservo"
crate-type = ["cdylib"]
test = false
bench = false

[dependencies]
# Todo: Evaluate how official this crate is.
ohos_hilog = "0.1.2"
getopts = { workspace = true }
ipc-channel = { workspace = true }
libc = { workspace = true }
# libloading = "0.8"
libservo = { path = "../../components/servo" }
log = { workspace = true }
serde_json = { workspace = true }
servo-media = { git = "https://github.com/servo/media" }
surfman = { workspace = true, features = ["sm-angle-default"] }
webxr = { git = "https://github.com/servo/webxr" }

[build-dependencies]
cc = "1.0"
gl_generator = "0.14"
serde_json = { workspace = true }
vergen = { version = "8.0.0", features = ["git", "gitcl"] }

[features]
debugmozjs = ["libservo/debugmozjs"]
# TODO: Once the native-bluetooth feature works for
# Android, re-add it here.
default = ["max_log_level"]
max_log_level = ["log/release_max_level_info"]
