[target.aarch64-linux-android]
linker = "aarch64-linux-android30-clang"

[target.armv7-linux-androideabi]
linker = "armv7a-linux-androideabi30-clang"

[target.armv-linux-androideabi]
linker = "armv7a-linux-androideabi30-clang"

[target.i686-linux-android]
linker = "i686-linux-android30-clang"

[target.x86_64-linux-android]
linker = "x86_64-linux-android30-clang"

[target.x86_64-pc-windows-msvc]
linker = "lld-link.exe"

[target.x86_64-uwp-windows-msvc]
linker = "lld-link.exe"

[target.i686-pc-windows-msvc]
linker = "lld-link.exe"

[target.aarch64-pc-windows-msvc]
linker = "lld-link.exe"

[target.aarch64-uwp-windows-msvc]
linker = "lld-link.exe"

[target.aarch64-unknown-linux-ohos]
ar = "/home/jschwender/tools/ohos-sdk/linux/native-linux-x64-4.0.10.13-Release/native/llvm/bin/llvm-ar"
linker = "aarch64-unknown-linux-ohos-clang.sh"

[env]
MACOSX_DEPLOYMENT_TARGET = "10.10"
RUSTC_BOOTSTRAP = "1"

[build]
rustdocflags = ["--document-private-items"]
# rustc = "crown"

[patch.crates-io]
napi-derive-ohos = { git = "https://github.com/jschwe/ohos-rs.git", branch = "jschwender/ohos" }
raw-window-handle = { git = "https://github.com/jschwe/raw-window-handle" , branch = "jschwender/ohos" }
# https://github.com/servo/rust-freetype/pull/72
freetype = { git = "https://github.com/jschwe/rust-freetype", branch = "jschwender/ohos" }
# raw-window-handle = { path = "/home/jschwender/Dev/raw-window-handle" }
# Status: Surfman is still being hacked on!
# surfman = { path = "/home/jschwender/Dev/surfman/surfman" }
surfman = { git = "https://github.com/jschwe/surfman" , branch = "jschwender/ohosv2" }
webxr = { git = "https://github.com/servo/webxr.git" }

# Waiting on new release
font-kit  = { git = "https://github.com/servo/font-kit" , branch = "main" }

# font-kit = { path = "/home/jschwender/Dev/font-kit"}

