[target.aarch64-linux-android]
linker = "aarch64-linux-android30-clang"

[target.armv7-linux-androideabi]
linker = "armv7a-linux-androideabi30-clang"

[target.armv-linux-androideabi]
linker = "armv7a-linux-androideabi30-clang"

[target.i686-linux-android]
linker = "i686-linux-android30-clang"

[target.x86_64-linux-android]
linker = "x86_64-linux-android30-clang"

[target.x86_64-pc-windows-msvc]
linker = "lld-link.exe"

[target.x86_64-uwp-windows-msvc]
linker = "lld-link.exe"

[target.i686-pc-windows-msvc]
linker = "lld-link.exe"

[target.aarch64-pc-windows-msvc]
linker = "lld-link.exe"

[target.aarch64-uwp-windows-msvc]
linker = "lld-link.exe"

[target.aarch64-unknown-linux-ohos]
ar = "/home/jschwender/tools/ohos-sdk/linux/native-linux-x64-4.0.10.13-Release/native/llvm/bin/llvm-ar"
linker = "aarch64-unknown-linux-ohos-clang.sh"

[unstable]
build-std = ["core", "alloc", "std"]

[env]
MACOSX_DEPLOYMENT_TARGET = "10.10"
RUSTC_BOOTSTRAP = "1"

[build]
rustdocflags = ["--document-private-items"]
rustc = "crown"

