#name: Linux
#on: push
#env:
#  RUST_BACKTRACE: 1
#  SHELL: /bin/bash
#
#jobs:
#  # dummy commit
#  build:
#    name: Linux Build
#    runs-on: ["self-hosted"]
#    steps:
#      # Faster checkout for self-hosted runner that uses prebaked repo.
#      - if: ${{ github.event_name != 'pull_request_target' }}
#        run: git fetch --depth=1 origin $GITHUB_SHA
#      - if: ${{ github.event_name == 'pull_request_target' }}
#        run: git fetch --depth=1 origin ${{ github.event.pull_request.head.sha }}
#      - run: |
#          git switch --detach
#          git reset --hard FETCH_HEAD
#
#      # Always install crown, even on self-hosted runners, because it is tightly
#      # coupled to the rustc version, and we may have the wrong version if the
#      # commit we are building uses a different rustc version.
#      - name: Install crown
#        run: cargo install --path support/crown
#
#      - name: Build (${{ inputs.profile }})
#        run: |
#          ./mach build --locked --${{ inputs.profile }} --features "layout_2013"
#          cp -r target/cargo-timings target/cargo-timings-linux
#      - name: Smoketest
#        run: xvfb-run python3 ./mach smoketest --${{ inputs.profile  }}
#      - name: Script tests
#        run: ./mach test-scripts
#      - name: Unit tests
#        if: ${{ inputs.unit-tests }}
#        uses: nick-fields/retry@v3
#        with:
#          timeout_minutes: 20
#          max_attempts: 2 # https://github.com/servo/servo/issues/30683
#          command: python3 ./mach test-unit --${{ inputs.profile }}
#
#
#
#
#
#
