name: OpenHarmony
on: push

env:
  RUST_BACKTRACE: 1
  SHELL: /bin/bash
  CARGO_INCREMENTAL: 0

jobs:
  build:
    name: OpenHarmony Build
    runs-on: self-hosted
    strategy:
      matrix:
        target: ['aarch64-unknown-linux-ohos'] #, 'x86_64-unknown-linux-ohos']
    steps:
#      - uses: actions/checkout@v4
#        if: github.event_name != 'pull_request_target'
#        with:
#          fetch-depth: 2
      # Faster checkout for self-hosted runner that uses prebaked repo.
      - if: ${{ github.event_name != 'pull_request_target' }}
        run: git fetch --depth=1 origin $GITHUB_SHA
      - if: ${{ github.event_name == 'pull_request_target' }}
        run: git fetch --depth=1 origin ${{ github.event.pull_request.head.sha }}
      - run: |
          git switch --detach
          git reset --hard FETCH_HEAD
      # This is necessary to checkout the pull request if this run was triggered via a
      # `pull_request_target` event.
      - uses: actions/checkout@v4
        if: github.event_name == 'pull_request_target'
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2
      - name: Test hdc
        run: hdc list targets && hdc shell echo hello world
      - name: Build (arch ${{ matrix.target }} profile
        run: |
          ./mach build --locked --target ${{ matrix.target }} --release --flavor=harmonyos --no-default-features --features tracing --features tracing-hitrace
      - name: Install
        run: ./mach install --target ${{ matrix.target }} --release --flavor=harmonyos
      - name: Run app
        # Todo: perhaps load a website from the host?
        run:  |
          hdc shell aa start -a EntryAbility -b org.servo.servoshell -U https://servo.org --ps=--prefs js.disable_jit=true
          sleep 5
          hdc shell snapshot_display -f /data/local/tmp/servo0.jpeg
          hdc file recv /data/local/tmp/servo0.jpeg  servo_hos_screenshot.jpeg
      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        with:
          path: servo_hos_screenshot.jpeg
